# Generated by Django 2.2.4 on 2019-09-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0002_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcard',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
