# Generated by Django 2.2.4 on 2019-09-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateme', '0003_auto_20190912_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcard',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ratingcard',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ratingcard',
            name='url',
            field=models.CharField(blank=True, max_length=2047, null=True, unique=True),
        ),
    ]
